### ISSUE TITLE
can i contribute ?

### ISSUE THREAD

**Issue by kartikeyasaran** [mongzino/pyqt5-calculator#11]
I am a Python Developer and like to contribute in your project i can make changes in readme.md file and ui of your calculator app will you allow me to that . I am asking for merging the Pull Request ...... @mongzino

**Comment by mongzino** [comment]
sorry to late reply
first, thanks for your message but i am student and it's just my practice in class, not important project.
and actually i'm not good at using github project.
so if you want to contribute to this, you could
but you don't have to contribute this
